// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKVTr7evjBI8KubBP85Mvj9onA6hKgv9o',
    appId: '1:711509633700:web:e41734d88103fe38ac9431',
    messagingSenderId: '711509633700',
    projectId: 'chat-app-project-54d49',
    authDomain: 'chat-app-project-54d49.firebaseapp.com',
    storageBucket: 'chat-app-project-54d49.appspot.com',
    measurementId: 'G-NLTLE2DHQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOqKNA8MIuhIUTga3ctmaINh0_oZYUjyo',
    appId: '1:711509633700:android:e07afcebf5f4e824ac9431',
    messagingSenderId: '711509633700',
    projectId: 'chat-app-project-54d49',
    storageBucket: 'chat-app-project-54d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8rPfNHDFcqeC9G7KjC81DmugA_52bTGE',
    appId: '1:711509633700:ios:7c0f7bb30bee8d91ac9431',
    messagingSenderId: '711509633700',
    projectId: 'chat-app-project-54d49',
    storageBucket: 'chat-app-project-54d49.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8rPfNHDFcqeC9G7KjC81DmugA_52bTGE',
    appId: '1:711509633700:ios:94ebb457d794dda2ac9431',
    messagingSenderId: '711509633700',
    projectId: 'chat-app-project-54d49',
    storageBucket: 'chat-app-project-54d49.appspot.com',
    iosBundleId: 'com.example.chatty.RunnerTests',
  );
}
